environment:
  grid_size: 64
  max_steps: 1000
  robot_radius: 0.5
  coverage_resolution: 0.5

rewards:
  coverage_gain: 10.0
  time_penalty: 0.1
  collision_penalty: 50.0
  boundary_penalty: 30.0
  return_bonus: 100.0

training:
  total_timesteps: 1000000
  save_freq: 10000
  eval_freq: 5000
  n_eval_episodes: 10
